### ISSUE TITLE
Milestone 2 feedback:

### ISSUE THREAD

**Issue by Abu-Hijleh** [data301-2020-winter2/course-project-group_1047#6]
Must fix: 

- [ ] the data csv file should be referenced from the data/processed folder through relative addressing. Do not make copy csv files in your individual folders.
- [ ] Add to your individual read me to show you practiced markdown styles (test out things like lists, lines, bold, ect. as long as you test out at least 3 things in each read me) - this applies to mohammad and raunak, not sang.
- [ ] Use markdown to style task 5 better so that you can tell when each research question starts/ends and what the question is.
